HW09 is completed
mmart-pro/otusGo pull request #11
Opened 2024-01-05 15:29 UTC by mmart-pro

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-01-19 03:55 UTC, dshemin requested changes

2024-01-19 03:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			return []error{} // len = 0 => ok
Важно:

Можно просто вернуть nil без лишнего выделения памяти.

2024-01-19 03:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			res = append(res, ErrInvalidValidator)
Критично:

Обратите внимание на текст задания, у нас должно быть два типа ошибок: программные ошибки (когда программист сделал что-то не так) ИЛИ ошибки валидации (когда пользователь сделал что-то не так).

Иными словами, если неправильно сконфигурировали валидатор, надо вернуть ошибку сразу.

2024-01-19 03:55 UTC, dshemin commented on hw09_struct_validator/validator_test.go
> +	err := Validate(0)
Важно:

Используйте табличные тесты тут. Это будет более наглядно и легче в интерпритации вывод тестового фреймворка.

2024-01-19 03:55 UTC, dshemin commented on hw09_struct_validator/validators/validators_int.go
> +		return nil // unsupported validator
Важно:

В таком случае программист никогда не поймёт что он сделал что-то не то и будет пологать что программа работает корректно. Но это не так. Верните программную ошибку тут.

Данная проблема повторяется во многих местах. везде указывать не буду, пройдитесь по коду и поправьте пожалуйтса.

2024-01-20 06:43 UTC, mmart-pro commented on hw09_struct_validator/validator.go
> +			return []error{} // len = 0 => ok
исправил

2024-01-20 06:43 UTC, mmart-pro commented on hw09_struct_validator/validator.go
> +			res = append(res, ErrInvalidValidator)
не плохо было бы примеры в задании приводить, я это по-другому прочитал
разделил, вернул сразу

2024-01-20 06:43 UTC, mmart-pro commented on hw09_struct_validator/validator_test.go
> +	err := Validate(0)
переделал

2024-01-20 06:44 UTC, mmart-pro commented on hw09_struct_validator/validators/validators_int.go
> +		return nil // unsupported validator
переделал

2024-01-21 07:33 UTC, dshemin approved these changes

2024-01-22 05:21 UTC, merged