hw13_calendar
mmart-pro/otusGo pull request #14
Opened 2024-02-25 15:16 UTC by mmart-pro

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-02-26 15:06 UTC, dshemin requested changes

2024-02-26 15:06 UTC, dshemin commented on hw12_13_14_15_calendar/api/eventservice/eventservice.proto
> +  rpc CreateEvent(Event) returns (CreateEventResponse) {
Важно:

Тут мы принимаем сообщение в котором есть id, но мы его не используем. Лучше разделить сообщение хотя бы на на CreateEvent, без id, и Event.

2024-02-27 17:00 UTC, mmart-pro commented on hw12_13_14_15_calendar/Makefile
> +generate:
исправил на //go:generate

2024-02-27 17:00 UTC, mmart-pro commented on hw12_13_14_15_calendar/api/eventservice/eventservice.proto
> +  rpc CreateEvent(Event) returns (CreateEventResponse) {
заменил на CreateEventRequest

2024-02-28 00:43 UTC, dshemin approved these changes

2024-03-02 10:09 UTC, merged